CREATE TABLE IF NOT EXISTS signoz_index_v2 (
  timestamp DateTime64(9) CODEC(DoubleDelta, LZ4),
  traceID String CODEC(ZSTD(1)),
  spanID String CODEC(ZSTD(1)),
  parentSpanID String CODEC(ZSTD(1)),
  serviceName LowCardinality(String) CODEC(ZSTD(1)),
  name LowCardinality(String) CODEC(ZSTD(1)),
  kind Int32 CODEC(T64, ZSTD(1)),
  durationNano UInt64 CODEC(T64, ZSTD(1)),
  tags Array(String) CODEC(ZSTD(1)),
  tagsKeys Array(String) CODEC(ZSTD(2)),
  tagsValues Array(String) CODEC(ZSTD(2)),
  statusCode Int64 CODEC(T64, ZSTD(1)),
  references String CODEC(ZSTD(2)),
  externalHttpMethod LowCardinality(String) CODEC(ZSTD(1)),
  externalHttpUrl LowCardinality(String) CODEC(ZSTD(1)),
  component LowCardinality(String) CODEC(ZSTD(1)),
  dbSystem LowCardinality(String) CODEC(ZSTD(1)),
  dbName LowCardinality(String) CODEC(ZSTD(1)),
  dbOperation LowCardinality(String) CODEC(ZSTD(1)),
  peerService LowCardinality(String) CODEC(ZSTD(1)),
  events Array(String) CODEC(ZSTD(1)),
  httpMethod LowCardinality(String) CODEC(ZSTD(1)),
  httpUrl LowCardinality(String) CODEC(ZSTD(1)), 
  httpCode LowCardinality(String) CODEC(ZSTD(1)), 
  httpRoute LowCardinality(String) CODEC(ZSTD(1)), 
  httpHost LowCardinality(String) CODEC(ZSTD(1)), 
  msgSystem LowCardinality(String) CODEC(ZSTD(1)), 
  msgOperation LowCardinality(String) CODEC(ZSTD(1)),
  hasError Int32 CODEC(T64, ZSTD(1)),
  tagMap Map(LowCardinality(String), String) CODEC(ZSTD(2)),
  INDEX idx_traceID traceID TYPE bloom_filter GRANULARITY 4,
  INDEX idx_service serviceName TYPE bloom_filter GRANULARITY 4,
  INDEX idx_name name TYPE bloom_filter GRANULARITY 4,
  INDEX idx_kind kind TYPE minmax GRANULARITY 4,
  INDEX idx_tagsKeys tagsKeys TYPE bloom_filter(0.01) GRANULARITY 64,
  INDEX idx_tagsValues tagsValues TYPE bloom_filter(0.01) GRANULARITY 64,
  INDEX idx_duration durationNano TYPE minmax GRANULARITY 1
) ENGINE MergeTree()
PARTITION BY toDate(timestamp)
ORDER BY (timestamp, serviceName, kind, hasError)
SETTINGS index_granularity = 8192